language: android
sudo: true
script: "./gradlew clean install check"
os:
  - linux
before_install:
  - yes | sdkmanager "platforms;android-27"
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"

android:
  components:
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-27.0.3
    # The SDK version used to compile your project
    - android-27
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
